# Generated by Django 5.2.1 on 2026-08-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnloop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='estimated_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='habit',
            name='subject',
            field=models.CharField(choices=[('programming', 'Programming'), ('language', 'Language'), ('design', 'Design'), ('soft_skills', 'Soft Skills')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='subject',
            field=models.CharField(choices=[('programming', 'Programming'), ('language', 'Language'), ('design', 'Design'), ('soft_skills', 'Soft Skills')], max_length=50),
        ),
    ]
